title: SisfoK
email: deo@mail.com
description: >
  Menjadi manusia.
baseurl: ""
url: "https://sisfok.github.io/"
github_username:  deovaliandro

plugins:
  - jekyll-feed
  - jekyll-asciidoc

destination: ./public
markdown: kramdown
highlighter: rouge